[package]
name = "pw_checker"
version = "0.12.0"
edition = "2021"

[workspace]

[dependencies]
password-checker-core = { path = "../../core" }
risc0-zkvm = { path = "../../../../risc0/zkvm", default-features = false, features = [ "std" ] }
